#!/bin/sh
#script for downloading latest anime episode via torrent using torrent rss feeds on "subsplease.org/rss"


printf "\033[1;34mplease wait.. parsing Subsplease rss.."
data=$(curl -s "https://subsplease.org/rss/?r=1080" | tr "<|>" "\n")
name=$(printf "%s" "$data" | sed -nE 's/^\[.*Please\] (.*)/\1/p' | fzf)

[ -z "$name" ] && printf "\33[2K\r\033[1;31mNo anime selected\n" && exit 0 || printf "\33[2K\r\033[1;35mSelected >> \033[1;32m$name\n" 

	id=$(printf "$name" | sed -n -e 's/.*\[\(.*\)\].*/\1/p')
	magnet=$(printf "%s" "$data" | grep "$id%" | sed 's/amp;//g')
	options=("Download" "Stream")
	action=$(printf '%s\n' "${options[@]}" | fzf)

if [ "$action" == "Download" ]; then
    printf "\33[2K\r\033[1;35mDownloading >> \033[1;32m$name\n"
    aria2c --summary-interval=0 --console-log-level=warn --seed-time=0 "$magnet"

elif [ "$action" == "Stream" ]; then
    printf "\33[2K\r\033[1;35mStreaming >> \033[1;32m$name\n"
    webtorrent --mpv "$magnet"

fi
