# Shell variables
# Generated by 'wal'
wallpaper='/home/uzuto/Pictures/walls/ghost.jpg'

# Special
background='#070710'
foreground='#acb5ba'
cursor='#acb5ba'

# Colors
color0='#070710'
color1='#5D5C6B'
color2='#9C3F4E'
color3='#9A5E66'
color4='#E66055'
color5='#F59A58'
color6='#E9C964'
color7='#acb5ba'
color8='#787e82'
color9='#5D5C6B'
color10='#9C3F4E'
color11='#9A5E66'
color12='#E66055'
color13='#F59A58'
color14='#E9C964'
color15='#acb5ba'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"

# Don't Delete This File
